#!/bin/bash
# BLAAN v1.0.0 - Quick Reference Guide
# Everything you need to get LIVE & REAL system running

echo "🚀 BLAAN Trading Platform - Quick Reference"
echo "=============================================="
echo ""
echo "📌 WHAT IS BLAAN?"
echo "Real-time forex trading signals based on market news"
echo "Features: News analysis, lot sizing, risk management, secure authentication"
echo ""

echo "✅ WHAT'S INCLUDED (ALL LIVE & REAL):"
echo "  ✓ Real password hashing (bcrypt)"
echo "  ✓ JWT token authentication"
echo "  ✓ MongoDB database"
echo "  ✓ NewsAPI integration"
echo "  ✓ Risk calculations"
echo "  ✓ Multi-channel notifications"
echo ""

echo "🔧 SYSTEM REQUIREMENTS:"
echo "  • Python 3.9 or higher"
echo "  • Node.js 16 or higher"
echo "  • MongoDB (local or Atlas)"
echo "  • NewsAPI key (free: https://newsapi.org)"
echo ""

echo "📋 SETUP IN 5 MINUTES:"
echo ""
echo "Step 1: Run the setup script"
echo "  Linux/Mac:  bash START.sh"
echo "  Windows:    .\\START.ps1"
echo ""
echo "Step 2: Get your NewsAPI key"
echo "  → https://newsapi.org/register"
echo "  → Enter it when prompted"
echo ""
echo "Step 3: Configure environment"
echo "  → Edit backend/.env"
echo "  → Add NEWSAPI_KEY"
echo "  → Optional: Add DB, email, Telegram settings"
echo ""
echo "Step 4: Start the backend (Terminal 1)"
echo "  cd backend"
echo "  source venv/bin/activate    # Linux/Mac"
echo "  venv\\Scripts\\Activate.ps1   # Windows"
echo "  python main.py"
echo "  → API runs on http://localhost:5000"
echo ""
echo "Step 5: Start the frontend (Terminal 2)"
echo "  cd frontend"
echo "  npm run dev"
echo "  → App runs on http://localhost:5173"
echo ""
echo "Step 6: Open in browser"
echo "  → http://localhost:5173"
echo "  → Register a new account"
echo "  → Login with your credentials"
echo ""

echo "🧪 TESTING:"
echo ""
echo "Option 1: Automated validation"
echo "  python validate_setup.py"
echo ""
echo "Option 2: Manual API testing"
echo "  curl http://localhost:5000/health"
echo "  (See API_TESTING.md for 50+ test cases)"
echo ""
echo "Option 3: Test in browser"
echo "  1. Open http://localhost:5173"
echo "  2. Click 'Register'"
echo "  3. Fill in details (password must be 8+ chars)"
echo "  4. Click 'Login'"
echo "  5. You should see the dashboard"
echo ""

echo "🔑 KEY FEATURES TO TRY:"
echo ""
echo "[1] Authentication"
echo "  → Register with email & password"
echo "  → Passwords are REALLY hashed with bcrypt"
echo "  → JWT tokens protect API access"
echo ""
echo "[2] Trading Accounts"
echo "  → Create account on Dashboard"
echo "  → Set broker, balance, risk %"
echo "  → View account details"
echo ""
echo "[3] Market News"
echo "  → Go to 'News Center'"
echo "  → See real forex news from NewsAPI"
echo "  → Filter by currency pair (EUR, USD, GBP, JPY, etc.)"
echo ""
echo "[4] Risk Calculator"
echo "  → Click 'Risk Calculator'"
echo "  → Enter pip distance and leverage"
echo "  → See calculated lot size & risk amount"
echo "  → All calculations are REAL math"
echo ""
echo "[5] Trade Signals"
echo "  → Create new signal manually"
echo "  → Or check News Center for signal recommendations"
echo "  → All signals use REAL risk calculations"
echo ""

echo "📚 DOCUMENTATION:"
echo ""
echo "  README.md              - Full feature overview"
echo "  QUICK_START.md         - Extended setup guide"
echo "  API_TESTING.md         - 50+ test cases with examples"
echo "  LIVE_CHANGELOG.md      - What's new and REAL vs OLD"
echo "  ARCHITECTURE.md        - Technical details"
echo ""

echo "🐛 TROUBLESHOOTING:"
echo ""
echo "Backend won't start?"
echo "  1. Check: python --version (needs 3.9+)"
echo "  2. Check: pip install -r requirements.txt"
echo "  3. Check: MongoDB is running (mongod)"
echo "  4. Run:   python validate_setup.py"
echo ""
echo "MongoDB connection error?"
echo "  1. Local: mongod (in new terminal)"
echo "  2. Cloud: Set MONGODB_URI in .env"
echo "  3. Default: mongodb://localhost:27017"
echo ""
echo "Port 5000 in use?"
echo "  lsof -i :5000       # Find process"
echo "  kill -9 <PID>       # Kill it"
echo ""
echo "Frontend won't load?"
echo "  npm install          # Install dependencies"
echo "  npm run dev          # Start dev server"
echo "  http://localhost:5173 should appear"
echo ""
echo "Password validation failing?"
echo "  • Minimum 8 characters"
echo "  • Must include letters and numbers"
echo "  • ✓ 'SecurePass123'"
echo "  • ✗ 'short' or 'onlyletters'"
echo ""

echo "🎯 QUICK CURL TESTS:"
echo ""
echo "Test 1: Health check (database status)"
echo "  curl http://localhost:5000/health"
echo ""
echo "Test 2: Register user"
echo "  curl -X POST http://localhost:5000/api/auth/register \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"email\":\"test@test.com\",\"password\":\"Test123\",\"full_name\":\"Test User\"}'"
echo ""
echo "Test 3: Login user"
echo "  curl -X POST http://localhost:5000/api/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"email\":\"test@test.com\",\"password\":\"Test123\"}'"
echo "  → Copy the access_token from response"
echo ""
echo "Test 4: Access protected endpoint"
echo "  curl http://localhost:5000/api/auth/me \\"
echo "    -H 'Authorization: Bearer <YOUR_TOKEN_HERE>'"
echo ""
echo "Test 5: Get market news"
echo "  curl http://localhost:5000/api/news/categorized"
echo "  → Returns real news from NewsAPI"
echo ""
echo "See API_TESTING.md for 50+ more examples!"
echo ""

echo "🚀 YOU'RE READY TO START!"
echo ""
echo "Run this to begin:"
echo "  bash START.sh    (Linux/Mac)"
echo "  .\\START.ps1     (Windows)"
echo ""
echo "Questions? Check the docs or API_TESTING.md for examples"
echo ""
echo "Happy trading! 📈"
